### ISSUE TITLE
wETH center updaten

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#10]
**We have to remove some things from the wETH center**

- delet Approve Pool
- delet wrap
- delet unwrap
- make the menü smaller
- change the hover effect
- change the button style to the rosebud design

<img width="344" alt="Bildschirmfoto 2020-01-17 um 14 22 44" src="https://user-images.githubusercontent.com/43147663/72615519-34328f00-3935-11ea-9a7c-8a34d76eb2b5.png">

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
