### ISSUE TITLE
Improve visualization of "New Proposal" 

### ISSUE THREAD

**Issue by MaxKaay** [deora-earth/rosebudDAO#12]
Change colour of font and text to make entering information easier 

<img width="586" alt="Screenshot 2020-01-17 at 16 55 16" src="https://user-images.githubusercontent.com/45236782/72626475-0f491680-394b-11ea-8f32-d26e3e752d55.png">

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
