### ISSUE TITLE
Fix Progress bar % display

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#17]
<img width="536" alt="Bildschirmfoto 2020-01-22 um 16 47 15" src="https://user-images.githubusercontent.com/43147663/72909164-da680580-3d36-11ea-8261-cfa3ec674eda.png">

**Comment by simonweniger** [comment]
The red bar should start from the left and the green from the right

**Comment by MaxStalker** [comment]
@cyan-one can you explain in plain words what you are trying to achieve? :)

**Comment by simonweniger** [comment]
@MaxStalker The red percentage bar should start form the right...this is a [SemanticUI](https://react.semantic-ui.com/modules/progress/) component and I have no idea how i can change the styling form them. Overwriting the css doesnt work

**Comment by simonweniger** [comment]
currently there are two progress bar elements behind each other and both start from left. So we want the red one start from the right

**Comment by MaxStalker** [comment]
Aha!
Got it :)
