### ISSUE TITLE
First 4 bugs related to user-interactivity.

### ISSUE THREAD

**Issue by brunobettati** [deora-earth/rosebudDAO#23]
While operating RosebudDAO both as a non-member; then as a member, and then as a proposal-submitter, during this week i found some bugs. Since today they first two are not there anymore. Thus, i’d like to confirm that they did existed and that a team member actually worked on it.

Bug 1: (SOLVED) sometimes at pressing the button “members” it didn’t show all the pics, just a gray circle per person. It was alleatory. Now it is working ok.

Bug 2: (SOLVED) inside “members” sometimes you pressed on top of the pic of any of the members and it took you to… MolochDAO!

Bug 3: the pull-down menu of the login address (corner up right) “pulls down” on click, but when u move the mouse away, it doesn’t “pull up” again. To pull it up, you can click anywhere on the screen EXCEPT on the login address. When this happens in the menu “proposal” it is tricky, because it covers the button “New Proposal” which is below. This issue is easily solvable: you should pull-up this menu ANYWHERE u click on. It is confusing that u click again on the login address but the menu doesn’t go up again.

Bug 4: this one really cracked my head: When you submit a Proposal, Rosebud checks on (a) a DAI deposit approved (which operates automatically but you must remember to approve it from your wallet), but it also expects the tribute “to be approved by beneficiary.” So BEFORE you even prepare the Proposal for a benefitiary, the benefitary has to have approved the tribute. The thing is, including a test i just did, the benefitiary has to EACH TIME log in, go to the “DAI Center” and send any quantity, say 0.1 DAI (even if his DAI is already logged in and Rosebud shows how much he has available). This bug is a killer; first, because one of the fun parts is that somebody can make a proposal to your benefit without you knowing; second, in the case the proposal is a membership, a person who is not even a member anyhow has to go into Rosebud and send some DAI, which is something i will have to include in the tutorial.

This fourth bug might perhaps require a Github fix-it-together approach, but first please confirm my observation.

**Comment by simonweniger** [comment]
- you're right bug 1 and 2 are solved. (we deployed a new version on monday)
- bug 3 will be fixed with #24 
- bug 4 will be fixed with #21  and #20

**Comment by johba37** [comment]
@brunobettati  have we extracted the essence in #24 , #21 and #20? then i suggest to close

**Comment by brunobettati** [comment]
The bug indicated on post #23 is still not working, and therefore, since the new smart contract was deployed, i have not been able to submit any membership proposal for more than a week. This prevents me from moving forward into graphic overlay. 

<img width="2560" alt="Screenshot 2020-03-20 10 30 47" src="https://user-images.githubusercontent.com/59749599/77153506-26ff6100-6a9a-11ea-97b0-60132f516b40.png">
check screen captures. 
<img width="2560" alt="Screenshot 2020-03-20 10 33 38" src="https://user-images.githubusercontent.com/59749599/77153474-1b139f00-6a9a-11ea-91a1-88d413d06036.png">
