### ISSUE TITLE
dorpdown menu collapse 

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#24]
let the dropdown menu collaps when the user clicks on the button again 
<img width="410" alt="Bildschirmfoto 2020-01-29 um 14 32 56" src="https://user-images.githubusercontent.com/43147663/73360949-3f29df80-42a4-11ea-952b-de0fa04bdf56.png">

**Comment by MaxStalker** [comment]
@cyan-one are you gonna fix this one or need help? :)

**Comment by brunobettati** [comment]
I see it works exactly as it always did. It is non a "bug·", but it is annoying that the pull-down meniu does not pull up when you move the mouse away, the usual UX for click on pull-down menus.
