### ISSUE TITLE
set up production environment

### ISSUE THREAD

**Issue by johba37** [deora-earth/rosebudDAO#29]
# Bounty

set up latest contract and frontend on rosebud.fund

## Scope
- deploy latest contract with parameters
- set up domain + ssl
- set up redirct from `www.` to rosebud.fund

## Deliverables
- https://rosebud.fund to show frontend
- https://www.rosebud.fund, http://www.rosebud.fund & http://rosebud.fund to redirect correctly

## Gain for the project
- partially complete delivery

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @johannbarbie / 70%
bounty reviewer: @cyan-one  / 20%

**Comment by simonweniger** [comment]
- [x] All links working
- [x] https://www.rosebud.fund, http://www.rosebud.fund & http://rosebud.fund redirect correctly
- [x] Right version is deployed
- [x] [rosebud.fund](https://rosebud.fund) has a valid ssl certificate

<img width="1214" alt="Bildschirmfoto 2020-03-19 um 15 51 57" src="https://user-images.githubusercontent.com/43147663/77080792-07186080-69fa-11ea-911f-a1d62a38cf8d.png">
<img width="334" alt="Bildschirmfoto 2020-03-19 um 15 53 16" src="https://user-images.githubusercontent.com/43147663/77080805-0a135100-69fa-11ea-875c-934fb15b3e91.png">
