### ISSUE TITLE
page doesn't load if logged in user has logged out on metamask

### ISSUE THREAD

**Issue by johba37** [deora-earth/rosebudDAO#30]

**Comment by simonweniger** [comment]
![Bildschirmfoto 2020-03-11 um 11 29 33](https://user-images.githubusercontent.com/43147663/76407429-9fc03800-638b-11ea-8cd6-b5270c31e423.png)

**Comment by PumpkingWok** [comment]
Hi there,
I have just looked in it and i know what caused this bug, fell free to contact me if you still need help for it. Thanks in advance.

**Comment by simonweniger** [comment]
yes still need help. If you want you can solve it and make a PR
