### ISSUE TITLE
The progress bar is fixed in the proposal list view but has bugs in the proposal detail view

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#44]
The progress bar should look the same like in the proposal list view.

This is the current look in the detailed view:
![Bildschirmfoto 2020-03-16 um 14 56 02](https://user-images.githubusercontent.com/43147663/76766737-bce47480-6798-11ea-93ef-4371b9a46367.png)

**Comment by johba37** [comment]
closed by https://github.com/deora-earth/rosebudDAO/pull/46
