### ISSUE TITLE
Membership proposal does not accept "submit"

### ISSUE THREAD

**Issue by brunobettati** [deora-earth/rosebudDAO#47]
Submission of proposal does not proceed. 
This was a bug informed on #23, and solved  via #20 and #21.
But now with the fresh start after the new smart contract, as kickstarter i have not been able to submit first proposal.
1) I linked the invited member's wallet (Tomas Ives)
2) I ensured my wallet has enough DAI (315 DAI)
3) just in case, i added link to Rosebud's Forum where candiadate introduces himself.

Still, system throws an error.
We haven't began the graphic overlay and i can't proceed
<img width="2560" alt="Screenshot 2020-03-20 10 30 47" src="https://user-images.githubusercontent.com/59749599/77153799-bb69c380-6a9a-11ea-89e0-2f8ecc9c6b6d.png">
 without this basic function working.
check screen captures.
<img width="2560" alt="Screenshot 2020-03-20 10 33 38" src="https://user-images.githubusercontent.com/59749599/77153777-b1e05b80-6a9a-11ea-93d0-ee41a074890d.png">

**Comment by brunobettati** [comment]
![IMAGE 2020-03-21 13:07:30](https://user-images.githubusercontent.com/59749599/77226008-ef191c00-6b74-11ea-995e-44e525cf62b2.jpg)

Photo of inspector. From wjat I read, the problem is n the Gas.
I will stop finctionality for now and move into graphic overlay.

**Comment by brunobettati** [comment]
Still does not work. But some changes:
1. Now the "submit" option does not highlight white, meaning i can't click on it. But the photo reads "100 DAI deposit approved" and "Tribute approved by benefitary."
2. I went into Fund with Tomas' wallet on. I went into DAI center and put 100 and clicked on "Rosebud approved." 
3. transaction registered on Metamask and on Etherscan. see 2 screen captures.
4. I went back to Fund, this time as Bruno and redid proposal. Now the submit button is white or green, but clicking on it throws error. Inspector screen capture attached.

<img width="2560" alt="Screenshot 2020-03-23 21 20 03" src="https://user-images.githubusercontent.com/59749599/77360489-ba13f180-6d4d-11ea-8b0f-c68e2d3a9ee2.png">
<img width="2560" alt="Screenshot 2020-03-23 21 23 13" src="https://user-images.githubusercontent.com/59749599/77360498-bd0ee200-6d4d-11ea-901b-2056271792aa.png">
<img width="2560" alt="Screenshot 2020-03-23 21 28 26" src="https://user-images.githubusercontent.com/59749599/77360518-c730e080-6d4d-11ea-8ac8-5a6f072af76d.png">
<img width="2560" alt="Screenshot 2020-03-23 21 28 38" src="https://user-images.githubusercontent.com/59749599/77360522-c8faa400-6d4d-11ea-9afb-163863a3705a.png">
<img width="2560" alt="Screenshot 2020-03-23 21 23 39" src="https://user-images.githubusercontent.com/59749599/77360525-ca2bd100-6d4d-11ea-95b1-f0398f1caa38.png">

**Comment by johba37** [comment]
<img width="645" alt="Screen Shot 2020-03-24 at 12 19 14 PM" src="https://user-images.githubusercontent.com/659301/77420074-b58d1e80-6dc9-11ea-921d-6b2c42dc8c20.png">

i think i found the problem: only 50 DAI are approved from @brunobettati 's account, to the address of the DAO

**Comment by johba37** [comment]
i've create an issue here: https://github.com/deora-earth/rosebudDAO/issues/50 for @cyan-one 

@brunobettati to overcome the error immediately, you could use the DAI center and re-approve 100 DAI or more.

**Comment by brunobettati** [comment]
trying right now.

**Comment by brunobettati** [comment]
<img width="2560" alt="Screen Shot 2020-03-24 at 12 31 24" src="https://user-images.githubusercontent.com/59749599/77421041-68aa4780-6dcb-11ea-9c4c-017b151ba624.png">
 still same issue. Inspector now does not show any change

**Comment by johba37** [comment]
this has been solved, let's keep https://github.com/deora-earth/rosebudDAO/issues/50 open instead to sort out the UI.
