### ISSUE TITLE
creat Navigation

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#5]
### ToDO

**create a Navigation with:**

- Home 
- Members
- Proposals

**The Navigation elements should change depending on the current side.** 
- At Home it should display Members and Proposals.
- At Members it should display Home and Proposals.
- At Proposals it should display Home and Members.

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
