### ISSUE TITLE
check approval with right amount

### ISSUE THREAD

**Issue by johba37** [deora-earth/rosebudDAO#50]
the proposal has only 50 DAI approved:

<img width="645" alt="Screen Shot 2020-03-24 at 12 19 14 PM" src="https://user-images.githubusercontent.com/659301/77420149-d3f31a00-6dc9-11ea-8ea4-9fcd2dc5ae08.png">
but the UI displays incorrectly that the approval is enough:
<img width="442" alt="Screen Shot 2020-03-24 at 12 16 34 PM" src="https://user-images.githubusercontent.com/659301/77420145-d190c000-6dc9-11ea-860d-eafc953e5c7e.png">

## expectation:
UI should display an error for proposer approval

**Comment by brunobettati** [comment]
Success! I did the process from scratch, that is:
Member logged in, went into DAI center, pre-approved 100 DAI, left
Benefitiary logged in, went into DAI center, pre-approved 100 DAI, left.
Member logged in, submitted Proposal. Succcess.

I will modify in Forum the way this is explained. 
Now will try 2 more proposals: Alan and JOhann.

**Comment by MaxKaay** [comment]
But this bug is still present. It will become too complicated if the UI doesn't reflect the real status of the transaction ;)

**Comment by brunobettati** [comment]
I personally think that this black screen that only says "100 DAI deposit approved" and "ttribute approved by benefitiary" is really non-usr friendly. 
Why do u say bug is still present? ? ?

**Comment by johba37** [comment]
> Why do u say bug is still present? ?

because it displays a checkmark even if you approved less than 100 DAI

**Comment by brunobettati** [comment]
Yes and other issues as well, as i continue the UX. I've added a MILESTONE and linked this post to that.

**Comment by simonweniger** [comment]
solved with #54
