### ISSUE TITLE
Members Section

### ISSUE THREAD

**Issue by brunobettati** [deora-earth/rosebudDAO#51]
![04_rosebud_members](https://user-images.githubusercontent.com/59749599/78121431-ad596280-740b-11ea-864c-ec3c39acc805.jpg)
<img width="2560" alt="Screen Shot 2020-03-26 at 21 18 44" src="https://user-images.githubusercontent.com/59749599/77692699-63095900-6fa7-11ea-92ab-82f9b25d2cce.png">
This area has the following changes

What is called ELDERS is now 
**THE CITIZEN KANES OF ROSEBUD (major shareholders)
this section should show the biggest 5 shareholders, which must be updated automatically depending on approved membership proposals of new members.  

and what is called CONTRIBUTORS is now called
**THE ORSON WELLES OF ROSEBUD (minor shareholders)**
with all remaining shareholders.

**Comment by johba37** [comment]
> Please contact tomas@nectar.berlin with tech specs for graphic overlay.

as the Mountain will not come to Muhammad, the requirements will come to the repository. 

@brunobettati please remove the above section from this issue, it adds no value. Tomas will have to create a separate issue with specific requirements.

**Comment by brunobettati** [comment]
Done. 
As always, i continue  to learn the ways this team works and communicates. And so, Muhammad called me to ask the mountain: do you have any technical comments regarding the "specific requirements" to be submitted, or shall he just pronounce colour adjustments? 

Oh the meantime i will begin training of my partner on GitHub. This training business is neverending...

**Comment by MaxKaay** [comment]
@cyan-one  --> We can change the naming to **Citizen Kanes of Rosebud** & **THE ORSON WELLES OF ROSEBUD** .

Changing the existing structure of showing the +100 shares holder to the TOP 5 will be too difficult we have to postpone this unfortunately.

**Comment by brunobettati** [comment]
Ok.

can you do this manually say twice a week, while we leave this change for Rosebud V2.0?
I will write you an email due to commercial consideration.

**Comment by MaxKaay** [comment]
Doing these things twice a week manually would need even more effort. So we can not do this either unfortunately.

**Comment by MaxKaay** [comment]
Changes in Scope, see first comment.

Display of the TOP 5 shareholders instead of only showing the +100 shares needs changes in the function and complicated exchange with the Smart Contract: estimate **700 DAI**.

**Comment by brunobettati** [comment]
_> Display of the TOP 5 shareholders instead of only showing the +100 shares needs changes in the function and complicated exchange with the Smart Contract: estimate **700 DAI**._
Before deciding, explain to me how the algorithm works. Right now, we are asking (as per floating parameter) all new members to pay just 100 DAI. This is the case of "rightholders as members"

Does the section of "Citizen Kanes" publish any member that has MORE than 100 DAI? 
Is that the way it is working  now? 
To avoid further work and pay, either confirm to me this is the case.
If it is, but you cannot change it then i will modify floating parameter to 99 or 90 DAI as tribute. 

Thus automatically., members who pay MORE than 99 DAI, become "Citizen Kanes". And this will be the case with the other kind of member, the Investor, who will naturally wish to pay more so he gets more shares, while the other floating parameter, "1 share = 1 DAI" is respected.

**Comment by brunobettati** [comment]
I will make minor corrections on the reference slide, so that you know
- instead of _"100+ shares"_ i request it to say _(majority shareholders)_
- beside "The Orson Welles of Rosebud" i request to add _(minority shareholders)_

**Comment by MaxKaay** [comment]
@brunobettati to confirm: Everyone who owns more than 99 shares (like 100 or 1000) is part of the "Citizen Kanes" that's correct. So we can leave it as it is now.

@cyan-one  We are just changing the wording:
 ELDERS (100+ SHARES) --> **Citizen Kanes ((majority shareholders)**
CONTRIBUTORS --> **The Orson Welles of Rosebud**
