### ISSUE TITLE
Unify Members and Proposal Title 

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#6]
**The Head section of the Members and Proposal page should have the same look**

<img width="1119" alt="Bildschirmfoto 2020-01-17 um 13 54 23" src="https://user-images.githubusercontent.com/43147663/72613797-ea47aa00-3930-11ea-81a7-462cd251f8ad.png">

<img width="1104" alt="Bildschirmfoto 2020-01-17 um 13 54 32" src="https://user-images.githubusercontent.com/43147663/72613798-ea47aa00-3930-11ea-8392-c7eb2fc95480.png">

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
