### ISSUE TITLE
Member Page restyling

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#7]
### Style changes 

**Changes to do**
- make the member view white
- structure the shares and total value new
- change the tribute value lable 
- structure delegate key new
- structure History view new

<img width="1146" alt="Bildschirmfoto 2020-01-17 um 14 04 56" src="https://user-images.githubusercontent.com/43147663/72614360-655d9000-3932-11ea-8587-e739c23877cb.png">

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
