### ISSUE TITLE
Proposal page redesign

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#8]
**ToDO**

- give the main component the rosebud style 
- redesign and reposition the new proposal button
- redesing the voting lable
- give the title an h1 font
- give the description a p font
- restructure the shares and tribute display
- change the size of the proposal components (make them smaller)
- change the position and the color of yes and no votes

<img width="1100" alt="Bildschirmfoto 2020-01-17 um 14 12 16" src="https://user-images.githubusercontent.com/43147663/72614761-5e834d00-3933-11ea-91fb-7819833ee317.png">

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
