### ISSUE TITLE
Proposal view redesign

### ISSUE THREAD

**Issue by simonweniger** [deora-earth/rosebudDAO#9]
**ToDO**

- change the style of the description
- push everything more to the Top
- change the color of members name
- redesign the voting ends lable
- change the voters images to the new rosebud placholder images
- redesign the shares and total value display
- give the voting buttons 
- redesign eth deposit lable 
- give the voting buttons more padding

<img width="1198" alt="Bildschirmfoto 2020-01-17 um 14 12 51" src="https://user-images.githubusercontent.com/43147663/72614790-7529a400-3933-11ea-89b6-be957e0abfff.png">

**Comment by johba37** [comment]
resolved in https://github.com/deora-earth/rosebudDAO/pull/13
